<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0FSG5U65" failures="1" tests="1" name="Test" time="5.774" errors="0" timestamp="2025-01-03T09:45:37 IST">
  <testcase classname="testCases.TC002_LoginTest" name="verifyLogin" time="0.469">
    <failure type="java.lang.AssertionError" message="Test failed due to an unexpected error.">
      <![CDATA[java.lang.AssertionError: Test failed due to an unexpected error.
at testCases.TC002_LoginTest.verifyLogin(TC002_LoginTest.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- Test -->
